spring:
  datasource:
    mysql:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/shrekdata?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&
      username: root
      password: admin
    sqlservice:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      jdbc-url: jdbc:sqlserver://192.168.197.24:1433;DatabaseName=GzbusPB
      username: gzbuspb
      password:
  activiti:
      check-process-definitions: false
server:
  servlet:
      session:
          timeout: 3600
  port: 8090
mybatis:
   mapperLocations: classpath:/mapper/*.xml
prop:
   upload-folder: /opt/shrekspringboot/images/

  # /opt/shrekspringboot/images